### ISSUE TITLE
Error in calculating brightness when max_level is < 100

### ISSUE THREAD

**Issue by bdf0506** [schmittx/home-assistant-leviton-decora-smart-wifi#1]
There's an error in the formula that calculates the brightness when you are using a value that is less than 100. For example, if you set the max_level to 50%, a brightness value of 510 is calculated, when in actuality, the output should be 128 (127.5 rounded up).

https://github.com/schmittx/home-assistant-leviton-decora-smart-wifi/blob/3f08f977b116144fe8b111f2464861a5ef67fb29/custom_components/leviton_decora_smart_wifi/light.py#L79

The line probably should be:
`return int(self.device.brightness / self.device.max_level * 255)`

**Comment by schmittx** [comment]
Thanks for catching this, I've pushed an update which corrects this.
